version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: delivest-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delivest-network

  minio:
    image: minio/minio:latest
    container_name: delivest-minio
    command: server --console-address ":9001" /data/
    ports:
      - "${STORAGE_PORT}:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
    volumes:
      - minio-storage:/data
    networks:
      - delivest-network

  redis:
    image: redis:alpine
    container_name: delivest-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - delivest-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: delivest-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:delivest-redis:6379:0
    depends_on:
      - redis
    networks:
      - delivest-network

networks:
  delivest-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio-storage:
