// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/04/2026, 18:08:32
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/kirill/storage/site/delivest/apps/delivest-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/app/plugins/**/*.{js,ts,mjs}","/home/kirill/storage/site/delivest/apps/delivest-web/app/composables/**/*.{js,ts,mjs}","/home/kirill/storage/site/delivest/apps/delivest-web/app/utils/**/*.{js,ts,mjs}","/home/kirill/storage/site/delivest/apps/delivest-web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;