/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/header/AppHeader.vue')['default']
    AppMenu: typeof import('./src/components/app-menu/AppMenu.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BranchCard: typeof import('./src/components/branch/BranchCard.vue')['default']
    BranchCreateDialog: typeof import('./src/components/branch/BranchCreateDialog.vue')['default']
    BranchDeleteDialog: typeof import('./src/components/branch/BranchDeleteDialog.vue')['default']
    BranchEditDialog: typeof import('./src/components/branch/BranchEditDialog.vue')['default']
    BranchForm: typeof import('./src/components/branch/BranchForm.vue')['default']
    BranchSelectCard: typeof import('./src/components/branch/BranchSelectCard.vue')['default']
    Button: typeof import('primevue/button')['default']
    CategoryCard: typeof import('./src/components/category/CategoryCard.vue')['default']
    CategoryCreateDialog: typeof import('./src/components/category/CategoryCreateDialog.vue')['default']
    CategoryDeleteDialog: typeof import('./src/components/category/CategoryDeleteDialog.vue')['default']
    CategoryEditDialog: typeof import('./src/components/category/CategoryEditDialog.vue')['default']
    CategoryForm: typeof import('./src/components/category/CategoryForm.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    PermissionSelect: typeof import('./src/components/role/PermissionSelect.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RoleCard: typeof import('./src/components/role/RoleCard.vue')['default']
    RoleCreateDialog: typeof import('./src/components/role/RoleCreateDialog.vue')['default']
    RoleDeleteDialog: typeof import('./src/components/role/RoleDeleteDialog.vue')['default']
    RoleEditDialog: typeof import('./src/components/role/RoleEditDialog.vue')['default']
    RoleForm: typeof import('./src/components/role/RoleForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarSettings: typeof import('./src/components/app-menu/SidebarSettings.vue')['default']
    SidebarUserInfo: typeof import('./src/components/app-menu/SidebarUserInfo.vue')['default']
    StaffCard: typeof import('./src/components/staff/StaffCard.vue')['default']
    StaffCreateDialog: typeof import('./src/components/staff/StaffCreateDialog.vue')['default']
    StaffDeleteDialog: typeof import('./src/components/staff/StaffDeleteDialog.vue')['default']
    StaffEditDialog: typeof import('./src/components/staff/StaffEditDialog.vue')['default']
    StaffForm: typeof import('./src/components/staff/StaffForm.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
