/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/header/AppHeader.vue')['default']
    AppMenu: typeof import('./src/components/app-menu/AppMenu.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BranchCard: typeof import('./src/components/branch/BranchCard.vue')['default']
    BranchCreateDialog: typeof import('./src/components/branch/BranchCreateDialog.vue')['default']
    BranchDeleteDialog: typeof import('./src/components/branch/BranchDeleteDialog.vue')['default']
    BranchEditDialog: typeof import('./src/components/branch/BranchEditDialog.vue')['default']
    BranchSelectCard: typeof import('./src/components/branch/BranchSelectCard.vue')['default']
    Button: typeof import('primevue/button')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarSettings: typeof import('./src/components/app-menu/SidebarSettings.vue')['default']
    SidebarUserInfo: typeof import('./src/components/app-menu/SidebarUserInfo.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
