export const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).{8,}$/;
export const PHONE_REGEX = /^\+7\d{10}$/;
export const MIN_NAME_LENGTH = 1;
export const MAX_NAME_LENGTH = 100;
export const COOKIE_NAMES = {
  CLIENT_REFRESH_TOKEN: "client_refresh_token",
  STAFF_REFRESH_TOKEN: "staff_refresh_token",
  SESSION_ID: "session_id",
} as const;

export const Permission = {
  ADMIN: "ADMIN",

  // Работник
  STAFF_CREATE: "STAFF_CREATE",
  STAFF_READ: "STAFF_READ",
  STAFF_UPDATE: "STAFF_UPDATE",
  STAFF_DELETE: "STAFF_DELETE",

  // Клиент
  CLIENT_CREATE: "CLIENT_CREATE",
  CLIENT_READ: "CLIENT_READ",
  CLIENT_UPDATE: "CLIENT_UPDATE",
  CLIENT_DELETE: "CLIENT_DELETE",

  // Роль
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_READ: "ROLE_READ",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",

  // Продукт
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_READ: "PRODUCT_READ",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  // Категория
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_READ: "CATEGORY_READ",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  // Филиал
  BRANCH_CREATE: "BRANCH_CREATE",
  BRANCH_READ: "BRANCH_READ",
  BRANCH_UPDATE: "BRANCH_UPDATE",
  BRANCH_DELETE: "BRANCH_DELETE",

  // Заказ
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_READ: "ORDER_READ",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_DELETE: "ORDER_DELETE",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
