export const ErrorCodes = {
  // Общие ошибки
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  HTTP_ERROR: "HTTP_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  ACCESS_DENIED: "ACCESS_DENIED",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",

  // Auth ошибки
  LOGIN_FAILED: "LOGIN_FAILED",
  REFRESH_FAILED: "REFRESH_FAILED",
  REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  MISSING_TOKEN: "MISSING_TOKEN",
  INVALID_AUTH_SCHEME: "INVALID_AUTH_SCHEME",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  GET_PROFILE_ERROR: "GET_PROFILE_ERROR",
  USER_NOT_REGISTERED: "USER_NOT_REGISTERED",
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  RESEND_LIMIT_EXCEEDED: "RESEND_LIMIT_EXCEEDED",
  RESEND_TOO_FAST: "RESEND_TOO_FAST",

  // Изображения
  HEIC_CONVERSION_FAILED: "HEIC_CONVERSION_FAILED",
  IMAGE_INVALID_FORMAT: "IMAGE_INVALID_FORMAT",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",

  // Файлы
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_DELETE_FAILED: "FILE_DELETE_FAILED",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  MISSING_FILE: "MISSING_FILE",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_ACCESS_DENIED: "FILE_ACCESS_DENIED",
  FILE_RETRIEVAL_FAILED: "FILE_RETRIEVAL_FAILED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",

  // Пользователи
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  FAILED_TO_CREATE_ACCOUNT: "FAILED_TO_CREATE_ACCOUNT",
  FAILED_TO_UPDATE_ACCOUNT: "FAILED_TO_UPDATE_ACCOUNT",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
  UPDATE_USER_AVATAR_ERROR: "UPDATE_USER_ERROR",

  // Регистрация
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  DUPLICATE_VALUE: "DUPLICATE_VALUE",
} as const;
